spring.application.name=BookLibrary2

spring.datasource.url=${H2_DATASOURCE_URL}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${H2_DATASOURCE_USERNAME}
spring.datasource.password=${H2_DATASOURCE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true
spring.h2.console.path=/h2

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

jwt.secret-key=${JWT_SECRET_KEY}
jwt.expiration-time=3600000